packages:
  - apps/*
  - packages/*
  - e2e
overrides:
  dompurify: ^3.4.11
verifyDepsBeforeRun: error
enableGlobalVirtualStore: false
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  vue-demi: true
