-- AlterEnum: 16 neue Provider (Exchanges + Chains)
ALTER TYPE "ProviderId" ADD VALUE 'BINANCE';
ALTER TYPE "ProviderId" ADD VALUE 'OKX';
ALTER TYPE "ProviderId" ADD VALUE 'BYBIT';
ALTER TYPE "ProviderId" ADD VALUE 'KUCOIN';
ALTER TYPE "ProviderId" ADD VALUE 'BITSTAMP';
ALTER TYPE "ProviderId" ADD VALUE 'GATEIO';
ALTER TYPE "ProviderId" ADD VALUE 'CRYPTOCOM';
ALTER TYPE "ProviderId" ADD VALUE 'POLYGON';
ALTER TYPE "ProviderId" ADD VALUE 'ARBITRUM';
ALTER TYPE "ProviderId" ADD VALUE 'BASE';
ALTER TYPE "ProviderId" ADD VALUE 'BSC';
ALTER TYPE "ProviderId" ADD VALUE 'LITECOIN';
ALTER TYPE "ProviderId" ADD VALUE 'DOGECOIN';
ALTER TYPE "ProviderId" ADD VALUE 'CARDANO';
ALTER TYPE "ProviderId" ADD VALUE 'XRP';
ALTER TYPE "ProviderId" ADD VALUE 'TRON';
ALTER TYPE "ProviderId" ADD VALUE 'COSMOS';
